export enum ErrorCode {
  COMMON_NOT_FOUND = 'COMMON.NOT_FOUND',
  COMMON_NO_INPUT = 'COMMON.NO_INPUT',

  AUTH_UNAUTHORIZED = 'AUTH.UNAUTHORIZED',
  AUTH_TOKEN_EXPIRED = 'AUTH.TOKEN_EXPIRED',
  AUTH_REFRESH_TOKEN_EXPIRED = 'AUTH.REFRESH_TOKEN_EXPIRED',

  // 500
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
}
