export enum ErrorCode {
  COMMON_NOT_FOUND = 'COMMON_NOT_FOUND',
  COMMON_NO_INPUT = 'COMMON_NO_INPUT',

  AUTH_UNAUTHORIZED = 'AUTH_UNAUTHORIZED',
  AUTH_TOKEN_EXPIRED = 'AUTH_TOKEN_EXPIRED',
  AUTH_REFRESH_TOKEN_EXPIRED = 'AUTH_REFRESH_TOKEN_EXPIRED',

  // 500
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
}
